// src/models/TripTimeline.js
const mongoose = require('mongoose');

const TimelineEventSchema = new mongoose.Schema({
  eventId: {
    type: String,
    unique: true,
    required: true,
  },
  timestamp: {
    type: Date,
    required: true,
    index: true,
  },
  eventType: {
    type: String,
    enum: [
      'departure',
      'arrival',
      'photo_taken',
      'activity_completed',
      'meal',
      'accommodation_check_in',
      'accommodation_check_out',
      'transportation_start',
      'transportation_end',
      'journal_entry',
      'milestone',
      'expense',
      'location_update',
      'memory_created',
      'alert',
      'custom_event',
    ],
    required: true,
    index: true,
  },
  title: {
    type: String,
    required: true,
  },
  description: String,
  location: {
    name: String,
    address: String,
    coordinates: {
      latitude: Number,
      longitude: Number,
    },
  },
  relatedTo: {
    type: String, // Reference to activity, meal, accommodation, etc.
  },
  relatedModel: {
    type: String, // TouristPlace, Food, Hotel, etc.
  },
  relatedId: {
    type: mongoose.Schema.Types.ObjectId,
  },
  photos: [
    {
      url: String,
      caption: String,
    },
  ],
  metadata: {
    type: Map,
    of: String,
  },
  importance: {
    type: Number,
    enum: [1, 2, 3, 4, 5], // 1 = low, 5 = high/milestone
    default: 2,
  },
  cost: Number,
  duration: Number, // in minutes
  attendees: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
  ],
  sentimentScore: {
    type: Number,
    min: -1,
    max: 1,
  }, // AI sentiment from memories
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const TripTimelineSchema = new mongoose.Schema({
  tripId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Trip',
    required: true,
    unique: true,
    index: true,
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  events: [TimelineEventSchema],
  totalEvents: {
    type: Number,
    default: 0,
  },
  startDate: Date,
  endDate: Date,
  keyMilestones: [
    {
      eventId: String,
      title: String,
      description: String,
      timestamp: Date,
      importance: Number,
    },
  ],
  averageSentiment: {
    type: Number,
    min: -1,
    max: 1,
  },
  mostActiveDay: Date,
  activityBreakdown: {
    type: Map,
    of: Number, // eventType: count
  },
  isAutoGenerated: {
    type: Boolean,
    default: true,
  },
  lastUpdated: {
    type: Date,
    default: Date.now,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

TripTimelineSchema.index({ tripId: 1, 'events.timestamp': 1 });

module.exports = mongoose.model('TripTimeline', TripTimelineSchema);
